import React from "react";

export const recentList = [
  {
    id: 1,
    avatar: 'https://via.placeholder.com/150x150',
    title: 'Need a quick support on setting',
    description: [<span className="gx-link" key={1}>Joy Parish</span>, "  created ticket 15 mins ago"],
    status: 2
  }, {
    id: 2,
    avatar: 'https://via.placeholder.com/150x150',
    title: 'Pre-sale query about the product',
    description: [<span className="gx-link" key={2}>You</span>, " replied 2 days ago"],
    status: 1
  }, {
    id: 3,
    avatar: 'https://via.placeholder.com/150x150',
    title: 'Regarding customization service',
    description: [<span className="gx-link" key={3}>Joy Parish</span>, " replied 2 days ago"],
    status: 4
  }
];

export const popularList = [
  {
    id: 1,
    image: 'https://via.placeholder.com/1100x750',
    isFeatured: false,
    title: 'Beach side Villah ',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 3,
    baths: 3,
    area: '1400 m2',
    more: 1,
  },
  {
    id: 2,
    image: 'https://via.placeholder.com/1100x750',
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 2,
    baths: 2,
    area: '1100 m2',
    more: 2,
  },
  {
    id: 3,
    image: 'https://via.placeholder.com/1100x750',
    isFeatured: false,
    title: 'CB Jeni Lifestyle Homes',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 4,
    baths: 1,
    area: '1300 m2',
    more: 4,
  }
];
export const newJersy = [
  {
    id: 1,
    image: 'https://via.placeholder.com/1100x750',
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 3,
    baths: 3,
    area: '1400 m2',
    more: 1,
  },
  {
    id: 2,
    image: 'https://via.placeholder.com/1100x750',
    isFeatured: false,
    title: 'CB Jeni Lifestyle Homes',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 2,
    baths: 2,
    area: '1100 m2',
    more: 2,
  },
  {
    id: 3,
    image: 'https://via.placeholder.com/1100x750',
    isFeatured: false,
    title: 'Beach side Villah ',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 4,
    baths: 1,
    area: '1300 m2',
    more: 4,
  }
];
export const colorado = [
  {
    id: 1,
    image: 'https://via.placeholder.com/1100x750',
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 3,
    baths: 3,
    area: '1400 m2',
    more: 1,
  },
  {
    id: 2,
    image: 'https://via.placeholder.com/1100x750',
    isFeatured: false,
    title: 'Beach side Villah ',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 2,
    baths: 2,
    area: '1100 m2',
    more: 2,
  },
  {
    id: 3,
    image: 'https://via.placeholder.com/1100x750',
    isFeatured: false,
    title: 'CB Jeni Lifestyle Homes',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 4,
    baths: 1,
    area: '1300 m2',
    more: 4,
  }
];
export const albama = [
  {
    id: 1,
    image: 'https://via.placeholder.com/1100x750',
    isFeatured: false,
    title: 'Luxury family home at beach side',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 3,
    baths: 3,
    area: '1400 m2',
    more: 1,
  },
  {
    id: 2,
    image: 'https://via.placeholder.com/1100x750',
    isFeatured: false,
    title: 'Beach side Villah ',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 2,
    baths: 2,
    area: '1100 m2',
    more: 2,
  },
  {
    id: 3,
    image: 'https://via.placeholder.com/1100x750',
    isFeatured: false,
    title: 'CB Jeni Lifestyle Homes',
    subTitle: 'South Western Ave',
    name: 'John Nash',
    date: '2 days ago',
    prize: '$670,500',
    sqft: '$587/sqft',
    bedrooms: 4,
    baths: 1,
    area: '1300 m2',
    more: 4,
  }
];
